name: PHP Syntax Check


on: [push, pull_request]

jobs:
  php-lint:
    name: Check PHP Syntax
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3

   
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0' 
        extensions: mbstring, intl, pdo, pdo_mysql

   
    - name: Run PHP Lint
      run: |
        find . -name "*.php" -print0 | xargs -0 -n1 php -l